# Generated by Django 3.1.5 on 2021-01-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.AddField(
            model_name='post',
            name='profilePicture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
