# Generated by Django 3.1.5 on 2021-02-25 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210205_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profilePicture',
        ),
    ]
