# Generated by Django 3.1.5 on 2021-03-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210304_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpicture',
            name='image_name',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
